/*
Adrian Luis-Martinez
Assignment 10.4: Creating a Physical Model from a Logical Diagram from a Dataset
*/

# Creating AUTHOR table
CREATE TABLE AUTHOR(
Author_ID INT AUTO_INCREMENT,
Author_Name VARCHAR(50) NOT NULL,
CONSTRAINT PK_AUTHOR PRIMARY KEY(Author_ID)
);

# Creating PUBLISHER table
CREATE TABLE PUBLISHER(
Publisher_ID INT AUTO_INCREMENT,
Publisher_Name VARCHAR(50),
CONSTRAINT PK_PUBLISHER PRIMARY KEY(Publisher_ID)
);

# Creating BOOK table
CREATE TABLE BOOK(
Book_ID INT AUTO_INCREMENT,
Title VARCHAR(50) NOT NULL,
ISBN VARCHAR(20),
ISBN13 VARCHAR(20),
Average_Rating DECIMAL(3,2),
Language_Code VARCHAR(50),
Num_Pages INT,
Ratings_Count INT DEFAULT 0,
Text_Reviews_Count INT,
Publication_Date DATE,
CONSTRAINT PK_BOOK PRIMARY KEY(Book_ID)
);

# Create BOOK_AUTHOR table
CREATE TABLE BOOK_AUTHOR(
Book_ID INT,
Author_ID INT,
CONSTRAINT PK_BOOK_AUTHOR PRIMARY KEY(Book_ID,Author_ID),
CONSTRAINT FK_BOOK_AUTHOR_BOOK_ID FOREIGN KEY(Book_ID) REFERENCES BOOK(Book_ID),
CONSTRAINT FK_BOOK_AUTHOR_AUTHOR_ID FOREIGN KEY(Author_ID) REFERENCES AUTHOR(Author_ID)
);

# Create BOOK_PUBLISHER table
CREATE TABLE BOOK_PUBLISHER(
Book_ID INT,
Publisher_ID INT,
CONSTRAINT PK_BOOK_PUBLISHER PRIMARY KEY(Book_ID,Publisher_ID),
CONSTRAINT FK_BOOK_PUBLISHER_Book_ID FOREIGN KEY(Book_ID) REFERENCES BOOK(Book_ID),
CONSTRAINT FK_BOOK_PUBLISHER_Publisher_ID FOREIGN KEY(Publisher_ID) REFERENCES PUBLISHER(Publisher_ID)
);
